name: Android CI

on:
  push:
    branches: ["SP05_ci/cd_code"]
  pull_request:
    branches: ["SP05_ci/cd_code"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew assemble